apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crisisweave-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crisisweave-secret-store
  target:
    name: crisisweave-api-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: crisisweave/production/api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crisisweave-worker
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crisisweave-secret-store
  target:
    name: crisisweave-worker-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: crisisweave/production/worker
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crisisweave-parser
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crisisweave-secret-store
  target:
    name: crisisweave-parser-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: crisisweave/production/parser
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crisisweave-telemetry
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crisisweave-secret-store
  target:
    name: crisisweave-telemetry-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: crisisweave/production/telemetry
