apiVersion: v1
kind: ServiceAccount
metadata:
  name: crisisweave-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crisisweave-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crisisweave-parser
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crisisweave-migration
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crisisweave-ui
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crisisweave-telemetry
automountServiceAccountToken: false
